<a href="https://colab.research.google.com/github/2303A510A3/AIML1/blob/main/Assignment01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#part 1
#1 Lists
a = ["BMW", "sai",5,6,7,"teja"]
print(a)

#2 Arrays
import numpy as np
arr1 = np.array([2,5,6])
arr2 = np.array([5,7,8])
print(arr1)
print(arr2)

#3 Identify their type using type()
print(type(a))
print(type(arr1))
print(type(arr2))

#4Perform mathematical operations on these datasets created - multiplication, division,powerof
multiplication=arr1*arr2
print(multiplication)

division = arr1/arr2
print(division)

sub = arr1-arr2
print(sub)

print(f"Exponential values: {np.exp(arr1)}")

#5 Combine text with Numpy fuction to generate a textual output - ”Addition of Two:array1 +array 2
Addition = arr1+arr2
print(Addition)

#6 mplement np.sin(), log(), log2(), np.exp())
a=np.sin(arr1)
print(arr1)

b=np.log(arr1)
print(b)

c=np.log(arr2)
print(c)

d=np.exp((arr1))
print(d)


['BMW', 'sai', 5, 6, 7, 'teja']
[2 5 6]
[5 7 8]
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[10 35 48]
[0.4        0.71428571 0.75      ]
[-3 -2 -2]
Exponential values: [  7.3890561  148.4131591  403.42879349]
[ 7 12 14]
[2 5 6]
[0.69314718 1.60943791 1.79175947]
[1.60943791 1.94591015 2.07944154]
[  7.3890561  148.4131591  403.42879349]
